<?php

function registerEventPostType() {
	$labels = array(
		'name'                  => 'Events',
		'singular_name'         => 'Event',
		'menu_name'             => 'Events',
		'name_admin_bar'        => 'Event',
		'archives'              => 'Event Archives',
		'attributes'            => 'Event Attributes',
		'parent_item_colon'     => 'Parent Event:',
		'all_items'             => 'All Events',
		'add_new_item'          => 'Add New Event',
		'add_new'               => 'Add Event',
		'new_item'              => 'New Event',
		'edit_item'             => 'Edit Event',
		'update_item'           => 'Update Event',
		'view_item'             => 'View Event',
		'view_items'            => 'View Events',
		'search_items'          => 'Search Event',
		'not_found'             => 'Not found',
		'not_found_in_trash'    => 'Not found in Trash',
		'featured_image'        => 'Featured Image',
		'set_featured_image'    => 'Set featured image',
		'remove_featured_image' => 'Remove featured image',
		'use_featured_image'    => 'Use as featured image',
		'insert_into_item'      => 'Insert into event',
		'uploaded_to_this_item' => 'Uploaded to this event',
		'items_list'            => 'Events list',
		'items_list_navigation' => 'Events list navigation',
		'filter_items_list'     => 'Filter events list',
	);
	$args = array(
		'label'                 => 'Event',
		'description'           => 'Een event inplannen',
		'labels'                => $labels,
		'supports'              => array( 'title', 'editor', 'custom-fields' ),
		'taxonomies'            => array( 'location' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-calendar-alt',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => true,
		'publicly_queryable'    => true,
		'rewrite'               => true,
		'capability_type'       => 'post',
		'show_in_rest'          => true,
	);
	register_post_type( 'event', $args );
}
function registerGalleryPostType() {
	$labels = array(
		'name'                  => 'Gallery',
		'singular_name'         => 'Gallery Item',
		'menu_name'             => 'Gallery',
		'name_admin_bar'        => 'Gallery',
		'archives'              => 'Gallery Archives',
		'attributes'            => 'Gallery Attributes',
		'parent_item_colon'     => 'Parent Gallery Item:',
		'all_items'             => 'All Gallery Items',
		'add_new_item'          => 'Add New Gallery Item',
		'add_new'               => 'Add Gallery Item',
		'new_item'              => 'New Gallery Item',
		'edit_item'             => 'Edit Gallery Item',
		'update_item'           => 'Update Gallery Item',
		'view_item'             => 'View Gallery Item',
		'view_items'            => 'View Gallery',
		'search_items'          => 'Search Gallery Item',
		'not_found'             => 'Not found',
		'not_found_in_trash'    => 'Not found in Trash',
		'featured_image'        => 'Featured Image',
		'set_featured_image'    => 'Set featured image',
		'remove_featured_image' => 'Remove featured image',
		'use_featured_image'    => 'Use as featured image',
		'insert_into_item'      => 'Insert into gallery item',
		'uploaded_to_this_item' => 'Uploaded to this gallery item',
		'items_list'            => 'Gallery list',
		'items_list_navigation' => 'Gallery list navigation',
		'filter_items_list'     => 'Filter gallery list',
	);
	$args = array(
		'label'                 => 'Gallery Item',
		'description'           => 'Een item toevoegen aan de galerij',
		'labels'                => $labels,
		'supports'              => array( 'title', 'thumbnail' ),
		'taxonomies'            => array( 'holiday' ),
		'hierarchical'          => false,
		'public'                => true,
		'show_ui'               => true,
		'show_in_menu'          => true,
		'menu_position'         => 5,
		'menu_icon'             => 'dashicons-images-alt2',
		'show_in_admin_bar'     => true,
		'show_in_nav_menus'     => true,
		'can_export'            => true,
		'has_archive'           => false,
		'exclude_from_search'   => true,
		'publicly_queryable'    => true,
		'rewrite'               => false,
		'capability_type'       => 'post',
		'show_in_rest'          => true,
	);
	register_post_type( 'gallery_item', $args );
}

add_action( 'init', 'registerEventPostType' );
add_action( 'init', 'registerGalleryPostType' );